name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.3
  - seaborn=0.11.2
  - pandas=1.4.3
  - pip=22.1.2
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - pip:
      - wandb==0.12.19
      - ipywidgets==7.7.1