name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.26.1
  - ipython=8.4.0
  - notebook=6.4.12
  - jupyterlab=3.4.3
  - cookiecutter=2.1.1
  - matplotlib=3.5.2
  - pandas=1.4.3
  - git=2.32.0
  - pip=22.1.2
  - pip:
      - wandb==0.12.19
      - hydra-core==1.2.0
